### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by 335812350** [mlvlab/DAPT#2]
I appreciate your work, but I often have a question: RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu), please correct the code.

**Comment by erngcho** [comment]
@335812350 Hi. Sharing the error log or `output/log.txt` would be helpful for me to assist you.

**Comment by 335812350** [comment]
> @335812350 Hi. Sharing the error log or `output/log.txt` would be helpful for me to assist you.
Thank you for your reply. I have solved the problem.
