### ISSUE TITLE
Questions about Fig.1

### ISSUE THREAD

**Issue by JiahaoChen1** [mlvlab/DAPT#4]
Hi, I am very interested in the results in Fig.1. I want to know how to realize normalized T-SNE and what is the difference between T-SNE. Thanks!

**Comment by erngcho** [comment]
Hi, thank you for your interest in our work. We performed normalization to represent embeddings on the surface of a unit hypersphere. If normalization is not performed, embeddings might positioned inside the hypersphere. Thank you.
